name: 'Build and Publish Docker Image'
author: DevOps
description: 'Build and publish Docker image to ECR.'

inputs:
  ecr-repo-name:
    description: 'The name of the ECR repository to create. This is also used to tag the image.'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile to build.'
    required: true
  docker-context:
    description: 'The Docker context to build the Dockerfile from.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Create ECR Repository
      shell: bash
      run: aws ecr create-repository --repository-name ${{ inputs.ecr-repo-name }} --tags Key=repository,Value=SynergyDataSystems/${{ github.event.repository.name }} || echo "Repository exists already. Skipping creation."

    - name: Set up Docker Buildx
      id: buildx
      with:
        driver: docker
      uses: docker/setup-buildx-action@v3

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.docker-context }}
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:latest
